language: csharp
solution: LoklakDotNet.sln
install:
  - nuget restore LoklakDotNet.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild LoklakDotNet.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./LoklakDotNetTests/bin/Debug/LoklakDotNetTests.dll /-trait "Ignore_CI=user"
